/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.DAO_ChiTietHoanTra;
import dao.DAO_HoaDon;
import dao.DAO_HoaDonHoan;
import dao.DAO_KhachHang;
import dao.DAO_NhanVien;
import dao.DAO_SanPham;
import entity.ChiTietHoaDon;
import entity.ChiTietHoanTra;
import entity.HoaDon;
import entity.KhachHang;
import entity.LoaiKhachHang;
import entity.NhanVien;
import entity.SanPham;
import static java.awt.Component.TOP_ALIGNMENT;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bohie
 */
public class Form_HoaDonHoan extends javax.swing.JFrame {

    /**
     * Creates new form Form_HoaDonHoan
     */
    private static String maHDH;
    private static String maHD;
    private static double tienHoan;
    private static String lydo;
    private DAO_HoaDonHoan hdh_dao = new DAO_HoaDonHoan();
    private DAO_ChiTietHoanTra ctht_dao = new DAO_ChiTietHoanTra();
    private dao.DAO_HoaDon hd_dao = new DAO_HoaDon();
    private dao.DAO_SanPham sp_dao = new DAO_SanPham();
    private dao.DAO_KhachHang kh_dao = new DAO_KhachHang();
    private dao.DAO_NhanVien nv_dao = new DAO_NhanVien();
    private DefaultTableModel modelCTDonHoan;


    public Form_HoaDonHoan(String HDH, String HD,double tienHoanTra) {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        maHDH = HDH;
        maHD = HD;
        tienHoan = tienHoanTra;
        initComponents();
        modelCTDonHoan = (DefaultTableModel) tableXuatHoaDonHoan.getModel();
        DocDL();
        DocDLTB();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHoaDon = new javax.swing.JPanel();
        pblTren = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblThuNgan = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblKH = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblLoaiKH = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblKH1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableXuatHoaDonHoan = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        pnlGiua = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTongSoLuong = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtVAT = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        pnlDuoi = new javax.swing.JPanel();
        btnHoanThanh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHoaDon.setPreferredSize(new java.awt.Dimension(515, 790));
        pnlHoaDon.setLayout(new javax.swing.BoxLayout(pnlHoaDon, javax.swing.BoxLayout.Y_AXIS));

        pblTren.setLayout(new javax.swing.BoxLayout(pblTren, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BIÊN BẢN HOÀN ĐƠN HÀNG");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quận Gò Vấp,Thành phố Hồ Chí Minh");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cửa hàng thời trang BHTT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ĐT: 08214851251");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đc: 12 Nguyễn Văn Bảo, phường 4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel2)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel3)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel4)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel5)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pblTren.add(jPanel5);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jPanel14.setMaximumSize(new java.awt.Dimension(20, 32767));
        jPanel14.setPreferredSize(new java.awt.Dimension(20, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel14);

        jPanel12.setLayout(new java.awt.GridLayout(2, 2));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày:");
        jPanel12.add(jLabel6);
        jPanel12.add(lblNgay);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Thu ngân:");
        jPanel12.add(jLabel7);
        jPanel12.add(lblThuNgan);

        jPanel10.add(jPanel12);

        jPanel15.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel15.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel15);

        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã phiếu: ");
        jPanel11.add(jLabel8);
        jPanel11.add(lblMaPhieu);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Khách hàng: ");
        jPanel11.add(jLabel9);
        jPanel11.add(lblKH);

        jPanel10.add(jPanel11);

        jPanel17.setMaximumSize(new java.awt.Dimension(20, 32767));
        jPanel17.setPreferredSize(new java.awt.Dimension(20, 40));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel17);

        jPanel16.setLayout(new java.awt.GridLayout(2, 2));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Loại khách:");
        jPanel16.add(jLabel11);
        jPanel16.add(lblLoaiKH);
        jPanel16.add(jLabel13);
        jPanel16.add(lblKH1);

        jPanel10.add(jPanel16);

        jPanel13.setMaximumSize(new java.awt.Dimension(20, 32767));
        jPanel13.setPreferredSize(new java.awt.Dimension(20, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel13);

        pblTren.add(jPanel10);

        pnlHoaDon.add(pblTren);

        tableXuatHoaDonHoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản phẩm", "Số lượng", "Giá", "Thành tiền", "Lý do hoàn"
            }
        ));
        jScrollPane1.setViewportView(tableXuatHoaDonHoan);

        pnlHoaDon.add(jScrollPane1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlHoaDon.add(jPanel8);

        pnlGiua.setLayout(new javax.swing.BoxLayout(pnlGiua, javax.swing.BoxLayout.X_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        pnlGiua.add(jPanel4);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 122));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tổng số lượng :");
        jPanel2.add(jLabel10);

        txtTongSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(txtTongSoLuong);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("VAT của hóa đơn:");
        jPanel2.add(jLabel15);

        txtVAT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(txtVAT);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Khuyến mãi của hóa đơn:");
        jPanel2.add(jLabel14);

        txtKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(txtKhuyenMai);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tổng Cộng");
        jPanel2.add(jLabel12);

        txtTongCong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongCong.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(txtTongCong);

        pnlGiua.add(jPanel2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        pnlGiua.add(jPanel9);

        pnlHoaDon.add(pnlGiua);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlHoaDon.add(jPanel7);

        pnlDuoi.setLayout(new javax.swing.BoxLayout(pnlDuoi, javax.swing.BoxLayout.X_AXIS));

        btnHoanThanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setMaximumSize(new java.awt.Dimension(107, 40));
        btnHoanThanh.setPreferredSize(new java.awt.Dimension(107, 40));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });
        pnlDuoi.add(btnHoanThanh);

        jPanel1.setMaximumSize(new java.awt.Dimension(50, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        pnlDuoi.add(jPanel1);

        btnIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIn.setText("In biên bản");
        btnIn.setMaximumSize(new java.awt.Dimension(103, 40));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        pnlDuoi.add(btnIn);

        pnlHoaDon.add(pnlDuoi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    public void PrintBienBan(JPanel c){
         try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("BienBanHoanDon.pdf"));
            document.open();
            BaseFont bf = BaseFont.createFont("c:\\windows\\fonts\\times.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font1 = new Font(bf, 16, Font.BOLD);
            Font font2 = new Font(bf, 14, Font.NORMAL);
            Paragraph tenCuaHang = new Paragraph("Cửa hàng thời trang BHTT", font1);
            tenCuaHang.setAlignment(Element.ALIGN_CENTER);
            Paragraph diaChi = new Paragraph("Địa chỉ 12 Nguyễn Văn Bảo, phường 4 \n Quận Gò Vấp, thành phố Hồ Chí mình \n Điện thoại: 08214851251", font2);
            diaChi.setAlignment(Element.ALIGN_CENTER);
            Paragraph tenHoaDon = new Paragraph("BIÊN BẢN HOÀN ĐƠN\n\n", font1);
            tenHoaDon.setAlignment(Element.ALIGN_CENTER);
            PdfPTable tableTop = new PdfPTable(4);
            PdfPCell cell1 = new PdfPCell(new Phrase("Ngày:", font2));
            cell1.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell1);

            PdfPCell cell2 = new PdfPCell(new Phrase(lblNgay.getText(), font2));
            cell2.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell2);

            PdfPCell cell3 = new PdfPCell(new Phrase("Mã phiếu:", font2));
            cell3.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell3);

            PdfPCell cell4 = new PdfPCell(new Phrase(lblMaPhieu.getText(), font2));
            cell4.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell4);

            PdfPCell cell5 = new PdfPCell(new Phrase("Thu ngân:", font2));
            cell5.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell5);

            PdfPCell cell6 = new PdfPCell(new Phrase(lblThuNgan.getText(), font2));
            cell6.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell6);

            PdfPCell cell7 = new PdfPCell(new Phrase("Khách hàng:", font2));
            cell7.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell7);

            PdfPCell cell8 = new PdfPCell(new Phrase(lblKH.getText(), font2));
            cell8.setBorder(Rectangle.NO_BORDER);
            tableTop.addCell(cell8);
            
             PdfPTable tableLKH = new PdfPTable(4);
             PdfPCell cell9 = new PdfPCell(new Phrase("Loại khách hàng:", font2));
             cell9.setBorder(Rectangle.NO_BORDER);
             tableLKH.addCell(cell9);

             PdfPCell cell10 = new PdfPCell(new Phrase(lblLoaiKH.getText(), font2));
             cell10.setBorder(Rectangle.NO_BORDER);
             tableLKH.addCell(cell10);
             
             PdfPCell cell11 = new PdfPCell(new Phrase("", font2));
             cell11.setBorder(Rectangle.NO_BORDER);
             tableLKH.addCell(cell11);

             PdfPCell cell12 = new PdfPCell(new Phrase("" + "\n\n\n\n", font2));
             cell12.setBorder(Rectangle.NO_BORDER);
             tableLKH.addCell(cell12);

            PdfPTable tableND = new PdfPTable(5);
            tableND.setPaddingTop(TOP_ALIGNMENT);
            PdfPCell cot1 = new PdfPCell(new Phrase("Sản phẩm", font2));
            PdfPCell cot2 = new PdfPCell(new Phrase("Số lượng", font2));
            PdfPCell cot3 = new PdfPCell(new Phrase("Giá", font2));
            PdfPCell cot4 = new PdfPCell(new Phrase("Thành tiền", font2));
            PdfPCell cot5 = new PdfPCell(new Phrase("Lý do hoàn", font2));
            tableND.addCell(cot1);
            tableND.addCell(cot2);
            tableND.addCell(cot3);
            tableND.addCell(cot4);
            tableND.addCell(cot5);

            for (int i = 0; i < tableXuatHoaDonHoan.getModel().getRowCount(); i++) {
                tableND.addCell(new Phrase(tableXuatHoaDonHoan.getModel().getValueAt(i, 0).toString(), font2));
                tableND.addCell(tableXuatHoaDonHoan.getModel().getValueAt(i, 1).toString());
                tableND.addCell(tableXuatHoaDonHoan.getModel().getValueAt(i, 2).toString());
                tableND.addCell(tableXuatHoaDonHoan.getModel().getValueAt(i, 3).toString());
                tableND.addCell(new Phrase(tableXuatHoaDonHoan.getModel().getValueAt(i, 4).toString(),font2)+"\n\n\n");
            }
          
            PdfPTable tableBot = new PdfPTable(2);
            PdfPCell bot1 = new PdfPCell(new Phrase("Tổng số lượng: ", font2));
            bot1.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot1);
            
             PdfPCell bot2 = new PdfPCell(new Phrase(txtTongSoLuong.getText(), font2));
            bot2.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot2);
            
            PdfPCell bot3 = new PdfPCell(new Phrase("VAT của hóa đơn: ", font2));
            bot3.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot3);
            
            
            PdfPCell bot4 = new PdfPCell(new Phrase(txtVAT.getText(), font2));
            bot4.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot4);
            
          
            
             PdfPCell bot5 = new PdfPCell(new Phrase("Khuyến mãi hóa đơn: ", font2));
            bot5.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot5);
            
            PdfPCell bot6 = new PdfPCell(new Phrase(txtKhuyenMai.getText(), font2));
            bot6.setBorder(Rectangle.NO_BORDER);
            tableBot.addCell(bot6);
            
        
            
//            PdfPCell bot7 = new PdfPCell(new Phrase("Tiền khách đưa: ", font2));
//            bot7.setBorder(Rectangle.NO_BORDER);
//            tableBot.addCell(bot7);
//            
//             PdfPCell bot8 = new PdfPCell(new Phrase(lplTienKhachDua.getText(), font2));
//            bot8.setBorder(Rectangle.NO_BORDER);
//            tableBot.addCell(bot8);
//            
//             PdfPCell bot9 = new PdfPCell(new Phrase("Tiền thối lại: ", font2));
//            bot9.setBorder(Rectangle.NO_BORDER);
//            tableBot.addCell(bot9);
//            
//            
//             PdfPCell bot10 = new PdfPCell(new Phrase(lplTienThoi.getText(), font2));
//            bot10.setBorder(Rectangle.NO_BORDER);
//            tableBot.addCell(bot10);
            
            
            document.add(tenCuaHang);
            document.add(diaChi);
            document.add(tenHoaDon);
            document.add(tableTop);
            document.add(tableLKH);
            document.add(tableND);
            document.add(tableBot);
            document.close();
        } catch (Exception e) {
            //
        }
    }
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
         JOptionPane.showMessageDialog(null, "In biên bản thành công");
         this.setVisible(false);
        PrintBienBan(pnlHoaDon);
         try{
           File file =new File ("D:\\CodePTUD\\BHTT_JAVA\\BHTT\\BienBanHoanDon.pdf");
           if(file.exists()) {
               if(Desktop.isDesktopSupported()){
                   Desktop.getDesktop().open(file);
               }else{
                   JOptionPane.showMessageDialog(this, "Not Supported");
               }
           }else{
               JOptionPane.showMessageDialog(this, "File Not Exist");
           }
       }catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_btnInActionPerformed
    private void DocDL() {
        HoaDon hd = hd_dao.layHoaDonTheoMa(maHD);
        NhanVien nv = nv_dao.layNhanVienBangMa(hd.getNhanVien().getMaNV());
        KhachHang kh=hd.getKhachHang();
        LoaiKhachHang lkh=kh.getLoaiKhachHang();
        String km="0%";
        if(lkh.getMaLoaiKH().equals("LKH001"))
            km="10%";
        lblThuNgan.setText(nv.getTenNV());
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String ngay = sdf.format(hd.getNgayLap());
        lblNgay.setText(ngay);
        lblMaPhieu.setText(maHDH);
        lblKH.setText(kh.getTenKH());
        lblLoaiKH.setText(lkh.getTenLoai());
        txtVAT.setText("5%");
        txtKhuyenMai.setText(km);
        
    }

    private void DocDLTB() {
        ArrayList<ChiTietHoanTra> dscthd = ctht_dao.layDSCTHTBangMa(maHDH);
        SanPham sp ;
        int tongSL =0;
        double tongTien =0;
        for (ChiTietHoanTra ctht : dscthd) {
            sp =  sp_dao.laySanPhamBangMa(ctht.getSanPham().getMaSP());
            modelCTDonHoan.addRow(new Object[]{ctht.getSanPham().getTenSP(),ctht.getSoLuong(),sp.getGiaGoc(),ctht.getSoLuong()*sp.getGiaGoc(),ctht.getLyDoHoanTra().toString()});
            tongSL  = tongSL+ ctht.getSoLuong();
            tongTien= tongTien+ ctht.getSoLuong()*sp.getGiaGoc();
        }
        txtTongCong.setText(String.format("%,.1f", tienHoan) + " VND");
        txtTongSoLuong.setText(tongSL+"");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_HoaDonHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_HoaDonHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_HoaDonHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_HoaDonHoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_HoaDonHoan(maHDH, maHD,tienHoan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblKH1;
    private javax.swing.JLabel lblLoaiKH;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblThuNgan;
    private javax.swing.JPanel pblTren;
    private javax.swing.JPanel pnlDuoi;
    private javax.swing.JPanel pnlGiua;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JTable tableXuatHoaDonHoan;
    private javax.swing.JLabel txtKhuyenMai;
    private javax.swing.JLabel txtTongCong;
    private javax.swing.JLabel txtTongSoLuong;
    private javax.swing.JLabel txtVAT;
    // End of variables declaration//GEN-END:variables
}
