/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.BorderUIResource;

/**
 *
 * @author ACER
 */
public class GD_NhanVien extends javax.swing.JFrame {

    private static String username;

    /**
     * Creates new form MainEmployee
     */
    public GD_NhanVien(String _username) {
        username = _username;
        this.setUndecorated(true);
        this.setResizable(true);
        this.setVisible(true);

        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/tuisach.png")));
        setTitle("Thời trang nữ BHTT");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        GD_GioiThieu frGioiThieu = new GD_GioiThieu(username);
        openComponent(frGioiThieu);

        pnlTitleTaoDonHang.setVisible(false);
        pnlTitleDonHangHoan.setVisible(false);
        pnlTitleLichSuDonHang.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlNguoiDung = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        pnlSilde = new javax.swing.JPanel();
        pnlGioiThieu = new keeptoo.KGradientPanel();
        lblGioiThieu = new javax.swing.JLabel();
        icGioiThieu = new javax.swing.JLabel();
        pnlKhachHang = new keeptoo.KGradientPanel();
        lblKhachHang = new javax.swing.JLabel();
        icKhachHang = new javax.swing.JLabel();
        pnlDonHang = new keeptoo.KGradientPanel();
        lblDonHang = new javax.swing.JLabel();
        icDonHang = new javax.swing.JLabel();
        pnlTitleTaoDonHang = new javax.swing.JPanel();
        pnlTaoDonHang = new keeptoo.KGradientPanel();
        lblTaoHoaDon = new javax.swing.JLabel();
        icTaoDonHang = new javax.swing.JLabel();
        pnlTitleDonHangHoan = new javax.swing.JPanel();
        pnlDonHangHoan = new keeptoo.KGradientPanel();
        lblDonHangHoan = new javax.swing.JLabel();
        icTaoDonHoan = new javax.swing.JLabel();
        pnlTitleLichSuDonHang = new javax.swing.JPanel();
        pnlLichSuDonHang = new keeptoo.KGradientPanel();
        lblLichSuDonHang = new javax.swing.JLabel();
        icLichSuDonHang = new javax.swing.JLabel();
        pnlThongKe = new keeptoo.KGradientPanel();
        lblThongKe = new javax.swing.JLabel();
        icThongKe = new javax.swing.JLabel();
        pnlTroGiup = new keeptoo.KGradientPanel();
        lblTroGiup = new javax.swing.JLabel();
        icTroGiup = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(200, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMain.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlForm.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        pnlForm.setPreferredSize(new java.awt.Dimension(200, 2));
        pnlForm.setLayout(new java.awt.BorderLayout());
        pnlMain.add(pnlForm, java.awt.BorderLayout.CENTER);

        pnlMenu.setBackground(new java.awt.Color(249, 234, 249));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        pnlMenu.setPreferredSize(new java.awt.Dimension(250, 200));
        pnlMenu.setLayout(new java.awt.BorderLayout());

        pnlNguoiDung.setBackground(new java.awt.Color(255, 255, 255));

        lblChucVu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblChucVu.setText("Nhân viên");

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-employee-80.png"))); // NOI18N
        lblImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTen.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblTen.setText("Nguyễn Văn A");

        javax.swing.GroupLayout pnlNguoiDungLayout = new javax.swing.GroupLayout(pnlNguoiDung);
        pnlNguoiDung.setLayout(pnlNguoiDungLayout);
        pnlNguoiDungLayout.setHorizontalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                        .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlNguoiDungLayout.setVerticalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                        .addComponent(lblChucVu)
                        .addGap(18, 18, 18)
                        .addComponent(lblTen)
                        .addGap(23, 23, 23))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlNguoiDung, java.awt.BorderLayout.PAGE_START);

        pnlSilde.setBackground(new java.awt.Color(255, 255, 255));
        pnlSilde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSilde.setLayout(new javax.swing.BoxLayout(pnlSilde, javax.swing.BoxLayout.PAGE_AXIS));

        pnlGioiThieu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlGioiThieu.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlGioiThieu.setPreferredSize(new java.awt.Dimension(270, 40));
        pnlGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGioiThieuMouseClicked(evt);
            }
        });
        pnlGioiThieu.setLayout(new java.awt.BorderLayout());

        lblGioiThieu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        lblGioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiThieu.setText("GIỚI THIỆU");
        lblGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlGioiThieu.add(lblGioiThieu, java.awt.BorderLayout.CENTER);

        icGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trangChu.png"))); // NOI18N
        icGioiThieu.setText("\n");
        pnlGioiThieu.add(icGioiThieu, java.awt.BorderLayout.LINE_START);

        pnlSilde.add(pnlGioiThieu);

        pnlKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlKhachHang.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlKhachHang.setPreferredSize(new java.awt.Dimension(270, 40));
        pnlKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlKhachHangMousePressed(evt);
            }
        });
        pnlKhachHang.setLayout(new java.awt.BorderLayout());

        lblKhachHang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setText("KHÁCH HÀNG");
        pnlKhachHang.add(lblKhachHang, java.awt.BorderLayout.CENTER);

        icKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachHang.png"))); // NOI18N
        icKhachHang.setText("\n");
        pnlKhachHang.add(icKhachHang, java.awt.BorderLayout.LINE_START);

        pnlSilde.add(pnlKhachHang);

        pnlDonHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlDonHang.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlDonHang.setPreferredSize(new java.awt.Dimension(270, 40));
        pnlDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDonHangMouseClicked(evt);
            }
        });
        pnlDonHang.setLayout(new java.awt.BorderLayout());

        lblDonHang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        lblDonHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonHang.setText("ĐƠN HÀNG");
        lblDonHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDonHang.add(lblDonHang, java.awt.BorderLayout.CENTER);
        lblDonHang.getAccessibleContext().setAccessibleDescription("");

        icDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/donHang.png"))); // NOI18N
        icDonHang.setText("\n");
        pnlDonHang.add(icDonHang, java.awt.BorderLayout.LINE_START);

        pnlSilde.add(pnlDonHang);

        pnlTitleTaoDonHang.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitleTaoDonHang.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnlTitleTaoDonHang.setLayout(new java.awt.BorderLayout());

        pnlTaoDonHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkGradientFocus(50);
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setMaximumSize(new java.awt.Dimension(200, 40));
        pnlTaoDonHang.setPreferredSize(new java.awt.Dimension(220, 40));
        pnlTaoDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTaoDonHangMousePressed(evt);
            }
        });
        pnlTaoDonHang.setLayout(new java.awt.BorderLayout());

        lblTaoHoaDon.setBackground(new java.awt.Color(102, 0, 204));
        lblTaoHoaDon.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblTaoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaoHoaDon.setText("TẠO ĐƠN HÀNG");
        lblTaoHoaDon.setVerifyInputWhenFocusTarget(false);
        pnlTaoDonHang.add(lblTaoHoaDon, java.awt.BorderLayout.CENTER);

        icTaoDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taoDonHangMoi.png"))); // NOI18N
        icTaoDonHang.setText("\n");
        pnlTaoDonHang.add(icTaoDonHang, java.awt.BorderLayout.LINE_START);

        pnlTitleTaoDonHang.add(pnlTaoDonHang, java.awt.BorderLayout.EAST);

        pnlSilde.add(pnlTitleTaoDonHang);

        pnlTitleDonHangHoan.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitleDonHangHoan.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnlTitleDonHangHoan.setLayout(new java.awt.BorderLayout());

        pnlDonHangHoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkGradientFocus(50);
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlDonHangHoan.setPreferredSize(new java.awt.Dimension(220, 40));
        pnlDonHangHoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDonHangHoanMousePressed(evt);
            }
        });
        pnlDonHangHoan.setLayout(new java.awt.BorderLayout());

        lblDonHangHoan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        lblDonHangHoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonHangHoan.setText("TẠO ĐƠN HOÀN");
        pnlDonHangHoan.add(lblDonHangHoan, java.awt.BorderLayout.CENTER);

        icTaoDonHoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taoDonHangMoi.png"))); // NOI18N
        icTaoDonHoan.setText("\n");
        pnlDonHangHoan.add(icTaoDonHoan, java.awt.BorderLayout.LINE_START);

        pnlTitleDonHangHoan.add(pnlDonHangHoan, java.awt.BorderLayout.EAST);

        pnlSilde.add(pnlTitleDonHangHoan);

        pnlTitleLichSuDonHang.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitleLichSuDonHang.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnlTitleLichSuDonHang.setLayout(new java.awt.BorderLayout());

        pnlLichSuDonHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkGradientFocus(50);
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setMaximumSize(new java.awt.Dimension(200, 40));
        pnlLichSuDonHang.setPreferredSize(new java.awt.Dimension(220, 40));
        pnlLichSuDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLichSuDonHangMousePressed(evt);
            }
        });
        pnlLichSuDonHang.setLayout(new java.awt.BorderLayout());

        lblLichSuDonHang.setBackground(new java.awt.Color(102, 0, 204));
        lblLichSuDonHang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        lblLichSuDonHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLichSuDonHang.setText("LỊCH SỬ ĐƠN HÀNG");
        lblLichSuDonHang.setVerifyInputWhenFocusTarget(false);
        pnlLichSuDonHang.add(lblLichSuDonHang, java.awt.BorderLayout.CENTER);

        icLichSuDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lichSuDonHang.png"))); // NOI18N
        icLichSuDonHang.setText("\n");
        pnlLichSuDonHang.add(icLichSuDonHang, java.awt.BorderLayout.LINE_START);

        pnlTitleLichSuDonHang.add(pnlLichSuDonHang, java.awt.BorderLayout.EAST);

        pnlSilde.add(pnlTitleLichSuDonHang);

        pnlThongKe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlThongKe.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlThongKe.setPreferredSize(new java.awt.Dimension(270, 40));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlThongKeMousePressed(evt);
            }
        });
        pnlThongKe.setLayout(new java.awt.BorderLayout());

        lblThongKe.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("THỐNG KÊ");
        pnlThongKe.add(lblThongKe, java.awt.BorderLayout.CENTER);

        icThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongKe.png"))); // NOI18N
        icThongKe.setText("\n");
        pnlThongKe.add(icThongKe, java.awt.BorderLayout.LINE_START);

        pnlSilde.add(pnlThongKe);

        pnlTroGiup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        pnlTroGiup.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnlTroGiup.setPreferredSize(new java.awt.Dimension(270, 40));
        pnlTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTroGiupMousePressed(evt);
            }
        });
        pnlTroGiup.setLayout(new java.awt.BorderLayout());

        lblTroGiup.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        lblTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setText("TRỢ GIÚP");
        pnlTroGiup.add(lblTroGiup, java.awt.BorderLayout.CENTER);

        icTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/troGiup.png"))); // NOI18N
        icTroGiup.setText("\n");
        pnlTroGiup.add(icTroGiup, java.awt.BorderLayout.LINE_START);

        pnlSilde.add(pnlTroGiup);

        pnlMenu.add(pnlSilde, java.awt.BorderLayout.CENTER);

        btnDangXuat.setBackground(new java.awt.Color(252, 249, 250));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(102, 0, 102));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangXuat.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 153), 3, true));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(76, 40));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDangXuat, java.awt.BorderLayout.PAGE_END);

        pnlMain.add(pnlMenu, java.awt.BorderLayout.WEST);
        pnlMenu.getAccessibleContext().setAccessibleParent(this);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkGradientFocus(2600);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 153));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1155, 45));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BHTT Store");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        kGradientPanel1.add(jLabel3);

        pnlMain.add(kGradientPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void pnlTaoDonHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaoDonHangMousePressed

        GD_TaoDonHang frame = new GD_TaoDonHang(username);
        openComponent(frame);
        pnlTaoDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(164, 158, 213));
        lblTaoHoaDon.setForeground(new Color(102,0,102));
        icTaoDonHang.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
  
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlTaoDonHangMousePressed

    private void pnlKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMousePressed
        GD_KhachHang frKhachHang = new GD_KhachHang(username);
        openComponent(frKhachHang);
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(164, 158, 213));
        lblKhachHang.setForeground(new Color(102,0,102));
        icKhachHang.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));

        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlKhachHangMousePressed

    private void pnlThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMousePressed
        GD_NVThongKe fNVThongKe = new GD_NVThongKe(username);
        openComponent(fNVThongKe);
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(164, 158, 213));
        lblThongKe.setForeground(new Color(102,0,102));
        icThongKe.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        

               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlThongKeMousePressed

    private void pnlTroGiupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTroGiupMousePressed
        GD_NVTroGiup fNVTroGiup = new GD_NVTroGiup(username);
        openComponent(fNVTroGiup);
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(164, 158, 213));
        lblTroGiup.setForeground(new Color(102,0,102));
        icTroGiup.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               

        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlTroGiupMousePressed

    private void pnlDonHangHoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonHangHoanMousePressed
        GD_TaoDonHangHoan fLichSuDonHang = new GD_TaoDonHangHoan(username);
        openComponent(fLichSuDonHang);
        pnlDonHangHoan.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(164, 158, 213));
        lblDonHangHoan.setForeground(new Color(102,0,102));
        icTaoDonHoan.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        

        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlDonHangHoanMousePressed

    private void pnlDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonHangMouseClicked
        boolean flag = true;
        if (pnlTitleTaoDonHang.isVisible()) {
            flag = false;
            pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
            pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
            lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
            icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        }
        pnlTitleTaoDonHang.setVisible(flag);
        pnlTitleDonHangHoan.setVisible(flag);
        pnlTitleLichSuDonHang.setVisible(flag);
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(164, 158, 213));
        lblDonHang.setForeground(new Color(102,0,102));
        icDonHang.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        

        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        

    }//GEN-LAST:event_pnlDonHangMouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất ?", "Đăng xuất", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GD_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(GD_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(GD_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(GD_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
            GD_DangNhap dn =new GD_DangNhap();
            dn.setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn thoát chương trình ?", "Thoát chương trình",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void pnlGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGioiThieuMouseClicked
        GD_GioiThieu d_GioiThieu=new GD_GioiThieu(username);
        openComponent(d_GioiThieu);
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(164, 158, 213));
        lblGioiThieu.setForeground(new Color(102,0,102));
        icGioiThieu.setForeground(new Color(102,0,102));

        // trả lại màu

        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icLichSuDonHang.setForeground(new java.awt.Color(255, 255, 255));



//        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
//        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
    }//GEN-LAST:event_pnlGioiThieuMouseClicked

    private void pnlLichSuDonHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLichSuDonHangMousePressed
        GD_LichSuDonHang gd = new GD_LichSuDonHang(username);
        openComponent(gd);
        pnlLichSuDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlLichSuDonHang.setkStartColor(new java.awt.Color(164, 158, 213));
        lblLichSuDonHang.setForeground(new Color(102,0,102));
        icLichSuDonHang.setForeground(new Color(102,0,102));
        
        // trả lại màu
        pnlGioiThieu.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlGioiThieu.setkStartColor(new java.awt.Color(102, 0, 153));
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlKhachHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlKhachHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        icKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHang.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHang.setForeground(new java.awt.Color(255, 255, 255));
        icDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlThongKe.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlThongKe.setkStartColor(new java.awt.Color(102, 0, 153));
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        icThongKe.setForeground(new java.awt.Color(255, 255, 255));
               
        pnlTroGiup.setkEndColor(new java.awt.Color(255, 204, 204));
        pnlTroGiup.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        icTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlTaoDonHang.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlTaoDonHang.setkStartColor(new java.awt.Color(102, 0, 153));
        lblTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHang.setForeground(new java.awt.Color(255, 255, 255));
        
        pnlDonHangHoan.setkEndColor(new java.awt.Color(102, 0, 153));
        pnlDonHangHoan.setkStartColor(new java.awt.Color(102, 0, 153));
        lblDonHangHoan.setForeground(new java.awt.Color(255, 255, 255));
        icTaoDonHoan.setForeground(new java.awt.Color(255, 255, 255));
        

    }//GEN-LAST:event_pnlLichSuDonHangMousePressed
    // open frame when click panel
    void openComponent(JInternalFrame frame) {
        Component[] components = pnlForm.getComponents();
        Component component = null;
        for (int i = 0; i < components.length; i++) {
            component = components[i];
            if (component != null) {
                component.setVisible(false);
            }
        }
        pnlForm.add(frame);
        frame.setVisible(true);
    }

    // set color
    void setColor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(204, 232, 255));
        label.setForeground(new Color(33, 162, 72));
    }

    // rest color
    void resetColor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 255, 255));
        label.setForeground(new Color(0, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
//        Properties props = new Properties();
//
//        props.put("logoString", "my company");
//        props.put("licenseKey", "INSERT YOUR LICENSE KEY HERE");
//
//        props.put("selectionBackgroundColor", "180 240 197");
//        props.put("menuSelectionBackgroundColor", "180 240 197");
//
//        props.put("controlColor", "218 254 230");
//        props.put("controlColorLight", "218 254 230");
//        props.put("controlColorDark", "180 240 197");
//
//        props.put("buttonColor", "218 230 254");
//        props.put("buttonColorLight", "255 255 255");
//        props.put("buttonColorDark", "244 242 232");
//
//        props.put("rolloverColor", "218 254 230");
//        props.put("rolloverColorLight", "218 254 230");
//        props.put("rolloverColorDark", "180 240 197");
//
//        props.put("windowTitleForegroundColor", "0 0 0");
//        props.put("windowTitleBackgroundColor", "180 240 197");
//        props.put("windowTitleColorLight", "218 254 230");
//        props.put("windowTitleColorDark", "180 240 197");
//        props.put("windowBorderColor", "218 254 230");
//        McWinLookAndFeel.setCurrentTheme(props);
        
        UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_NhanVien(username);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JLabel icDonHang;
    private javax.swing.JLabel icGioiThieu;
    private javax.swing.JLabel icKhachHang;
    private javax.swing.JLabel icLichSuDonHang;
    private javax.swing.JLabel icTaoDonHang;
    private javax.swing.JLabel icTaoDonHoan;
    private javax.swing.JLabel icThongKe;
    private javax.swing.JLabel icTroGiup;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblDonHangHoan;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblLichSuDonHang;
    private javax.swing.JLabel lblTaoHoaDon;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTroGiup;
    private keeptoo.KGradientPanel pnlDonHang;
    private keeptoo.KGradientPanel pnlDonHangHoan;
    private javax.swing.JPanel pnlForm;
    private keeptoo.KGradientPanel pnlGioiThieu;
    private keeptoo.KGradientPanel pnlKhachHang;
    private keeptoo.KGradientPanel pnlLichSuDonHang;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNguoiDung;
    private javax.swing.JPanel pnlSilde;
    private keeptoo.KGradientPanel pnlTaoDonHang;
    private keeptoo.KGradientPanel pnlThongKe;
    private javax.swing.JPanel pnlTitleDonHangHoan;
    private javax.swing.JPanel pnlTitleLichSuDonHang;
    private javax.swing.JPanel pnlTitleTaoDonHang;
    private keeptoo.KGradientPanel pnlTroGiup;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
